silverstripe/silverstripe-versioned-snapshots

src/ActivityEntry.php
src/SnapshotPublishable.php
tests/SnapshotTest.php

AC
- Allows to list all changes between two versions of an owner (incl. direct and indirect owned relations)
https://github.com/silverstripe/silverstripe-versioned/issues/195

versioned activity feed implementation

---

_config/tests.yml
src/Dev/State/DisableSnapshots.php
src/SnapshotPublishable.php

This is now used to disable snapshots during tests (for performance and to reduce test bleed). Tests relying on snapshot functionality may resume snapshotting by using the resume API in your setUp function in your test
At the moment it's very possible (read; extremely likely)  that client code test will break with undefined tables. This is because there are _many_ more tables that are now affected when writing an "owned" record - there's a lot more tables that need scaffolding. I'll raise a separate issue about somehow expanding SapphireTest to correctly scaffold all required tables for a test - but my personal opinion is that we _really_ __really__ don't want to go down that highly complex route.

NEW Allow pausing snapshots globally

---

src/SnapshotPublishable.php
tests/SnapshotTest.php
tests/SnapshotTest/BaseJoin.php
tests/SnapshotTest/GalleryImageJoin.php

a many-many spec may not always refer to the base class for a relation
this changes the check from a string comparision with the base class to
an instanceof check

use instance check in getManyManyLinking call

---

src/SnapshotPublishable.php

`Versioned::get_versionnumber_by_stage` can return null, which throws an error here

FIX null being returned from get_published_version_number

---

.travis.yml
composer.json
src/SnapshotPublishable.php

The previous code assumed that all has_one relations on an object
pointed to objects that own this object. This is a false assumption; it
also caused a bug when the has_one pointed to an unversioned object.
Fixes #36

FIX: getChangedOwnership() only looks at *owned* has_one relations

---

src/Handler/Form/Handler.php
src/Snapshot.php
src/SnapshotItem.php

Because $obj->ID is set to 0 on a deleted record, this broke the existing
snapshot creation.
Relies on https://github.com/silverstripe/silverstripe-versioned/pull/280,
without which deletions are logged as another creation.
Fixes #33

FIX: Track deletions correctly

---

src/SnapshotPublishable.php

Issue: When creating a new page, in site tree page shows as a Modified page instead Draft page.
Full SiteTree view 
When inside a page - left side siteTree

Fix draft pages showing modified in sitetree

---

README.md
_config/config.yml
src/CsvBulkLoader/SaveListener.php
src/Handler/CsvBulkLoader/Handler.php

New snapshot for every row that's actually been created or changed.
Ideally we'd use createSnapshotEvent('CSV Import from <file>', [$objs]),
but that can be very resource intensive on bulk imports (PHP memory).
The bulk loader destroys the DataObject instances after loading them,
so we'd need to recreate them.
We could allow createSnapshot() to accept a map of "class => ID"
instead, and then recreate+destroy the DataObject instances on the fly.
For now, recording one snapshot per row is good enough.
Relies on https://github.com/silverstripe/silverstripe-framework/pull/9929

NEW CsvBulkLoader integration

---

src/ActivityEntry.php

Item object from snapshotItem was pulling the deleted version, this was caused by the changes we made on SnapshotItem::getItem() https://github.com/silverstripe/silverstripe-versioned-snapshots/pull/47 where it was grabbing all the versions including the deleted version.

Snapshot Item is pulling deleted version

---

_config/workflow.yml
src/Handler/Elemental/PageSaveHandler.php
src/Workflow/WorkflowExtension.php

This pull request adds event handlers that bind to workflow events for publish and unpublish to ensure that snapshots are created when content is published or unpublished via workflow actions.

NEW: Workflow support

---

_config/thirdparty.yml
src/Thirdparty/UsedOnTableExtension.php

The PR includes an extension to extend class `SilverStripe\Admin\Forms\UsedOnTable` and exclude the snapshot data objects from showing in the Files section Used on Tab.
Currently, the tab looks as follows,

Ensure snapshot data objects not visible in File used on tab

---

src/SnapshotPublishable.php

I need to please be able to extend this class while still having access to `getSnapshotsBetweenVersionsFilters()`.
We don't seem to have great support for Fluent at the moment. The query run as part of `getSnapshotsBetweenVersionsFilters()` (and `hasOwnedModifications()`) don't consider the Locale context.
I hope to have time to be able to property digest these methods and come up with some support for the module in the new year, but atm I'm between a rock and a hard place, and just need to be able to extend/replace/fix.
**Please and thank you**

Update visiblity of two SnapshotPublishable methods

---

src/Handler/Elemental/ArchiveElementHandler.php
src/Handler/Elemental/ModifyElementHandler.php
src/Handler/Form/UnpublishHandler.php
src/Snapshot.php
src/SnapshotHasher.php
src/SnapshotItem.php
src/SnapshotPublishable.php
tests/IntegrationTest.php
tests/SnapshotItemTest.php
tests/SnapshotPublishableTest.php
tests/SnapshotTestAbstract.php

* Static methods replaced with non-static singleton pattern
* Minor code cleanup of in-memory cache but still left it disabled
* Raw queries
* Deep integration
These will be covered separate change-sets
https://github.com/silverstripe/silverstripe-versioned-snapshots/issues/51

NEW: Static methods replaced with non-static singleton pattern.

---

README.md
src/ActivityEntry.php
src/Migration/MigrationService.php
src/Snapshot.php
src/SnapshotItem.php
src/SnapshotPublishable.php
tests/SnapshotItemTest.php
tests/SnapshotPublishableTest.php
tests/SnapshotTest.php

Compatibility changes for Fluent module. Instructions for Fluent module integration added to the docs.
`Version` is a special model property that should not be redefined on any model. `SnapshotItem` currently has a `Version` property which may cause some random issues (especially when forceChange() is called). This change renames `Version` to `ObjectVersion` to prevent random issues and it's also more accurate as the version refers to the related object not the item itself.
This represents a breaking change which is acceptable as this is part of a new major version.

# BUG: Fluent module compatibility

---

tests/SnapshotTest.php

Fix a unit test warning which breaks the test run.

BUG: PHP Unit 9 compatibility patch.

---

src/Snapshot.php
tests/SnapshotTest.php
tests/SnapshotTest/SimpleBlock.php
tests/SnapshotTestAbstract.php

Un-versioned origin objects need to bail out during the snapshot creation.
Replaces https://github.com/silverstripe/silverstripe-versioned-snapshots/pull/58

BUG: Origin versioned check.

---

_config/config.yml
src/Handler/Elemental/PageSaveHandler.php
src/ImplicitModification.php
src/RelationDiffer/ClearCacheExtension.php
src/RelationDiffer/RelationDiffCache.php
src/RelationDiffer/RelationDiffer.php
src/Snapshot.php
src/SnapshotPublishable.php
tests/Handler/Elemental/PageSaveHandlerTest.php
tests/RelationDifferTest.php

* In-memory cache for relation differ
* finishing incomplete implementation of in-memory cache
* unit tests cover both cache hits & misses
* minor code cleanup

NEW: In-memory cache for relation differ.

---

_config/config.yml
_config/elemental.yml
_config/thirdparty.yml
_config/workflow.yml
src/Handler/GridField/Action/ReorderHandler.php
src/Snapshot.php
tests/Handler/GraphQL/Middleware/RollbackHandlerTest.php
tests/IntegrationTest.php
tests/SnapshotPublishableTest.php
tests/SnapshotTest.php

* extension config uses named keys so they can be overridden if needed
* replacing all instances of array syntax with property syntax

MISC: Extensions config cleanup.

---

README.md
src/Migration/MigrateFluentObjectHashTask.php
src/Migration/MigrateObjectVersionTask.php

Covers `ObjectVersion` field rename and `SnapshotItem` Fluent setup.

NEW: Migration dev tasks for breaking changes.

---

src/ActivityEntry.php
src/Snapshot.php
src/SnapshotItem.php
src/SnapshotPublishable.php
tests/IncompleteDataTest.php
tests/IncompleteDataTest.yml

* fixed an issue with activity feed when we have incomplete versioned history data
* this is a valid case as old versioned history data may get deleted so we need to support this case
* extensibility improvements (remove static method)
* minor code cleanup

BUG: Incomplete data fix (missing some versioned history records).
